MOOC/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :lectures do
      resources :comments
      collection do
        get 'download'
      end
      member do
        put "like", to: "lectures#upvote"
        put "dislike", to: "lectures#downvote"
        put :spam
        delete :unspam
  end

end
  resources :courses
  get 'welcome/index'

  get 'pages/index'

  get 'pages/index'

  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations" }

  root 'welcome#index'

end

MOOC/app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
  mount_uploader :attachement, AttachmentUploader
  has_many :comments
  acts_as_votable
  has_and_belongs_to_many :users
  validates :content , :attachement, :image, :course_id, :title, :user_id, :presence => true
  validates :title, length: { minimum: 3 , maximum: 50}
  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader

end

MOOC/app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show, :edit, :update, :destroy, :spam, :unspam]
  before_action :authenticate_user!
  before_action :load_courses, only: [:new, :create, :update, :edit]

  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.all
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
      @comments=Comment.where(lecture_id: @lecture).order("created_at DESC")
  end


  # GET /lectures/new
  def new
      if !current_user.is_instructor
          redirect_to lectures_path
      else

          @lecture = Lecture.new
      end
  end

  # GET /lectures/1/edit
  def edit
      if !current_user.is_instructor
          redirect_to lectures_path
      end

  end

  # def download_file
  #   @lecture = Lecture.find(params[:id])
  #   send_file(@lecture.attachement.path,
  #       :disposition => 'attachment',
  #       :url_based_filename => false)
  # end

  # POST /lectures
  # POST /lectures.json
  def create
      if !current_user.is_instructor
          redirect_to lectures_path
      end
    @lecture = Lecture.new(lecture_params)
    @lecture.user_id=current_user.id

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json

  def update
      if !current_user.is_instructor
          redirect_to lectures_path
      end


    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url, notice: 'Lecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def upvote
  @lecture = Lecture.find(params[:id])
  @lecture.upvote_by current_user
    redirect_to @lecture
  end

def downvote
  @lecture = Lecture.find(params[:id])
  @lecture.downvote_by current_user
  redirect_to @lecture
end

def spam
   current_user.lectures << @lecture
   current_user.save
   redirect_to @lecture

end

 def unspam
   current_user.lectures.delete(@lecture)
   current_user.save
   redirect_to @lecture
 end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    def load_courses
      @courses=Course.where(user_id: current_user);
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      params.require(:lecture).permit(:title, :image, :content, :attachement, :course_id, :user_id)
    end
end

MOOC/app/helpers/lectures_helper.rb
module LecturesHelper
end

MOOC/app/views/lectures/_form.html.erb
<div class="container" style="width:40%; margin-top:60px;">
<%= form_for(@lecture) do |f| %>
  <% if @lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% @lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-group">
  <span class="input-group-addon">Add Title</span>
      <%= f.text_field :title, autofocus: true,class: "form-control",placeholder: "Title" %>
  </div>
  <span class="help-block"></span>


  <div class="input-group">
  <span class="input-group">Add Content:</span>
      <%= f.cktext_area :content, autofocus: true,class: "form-control" %>
  </div>
  <span class="help-block"></span>

  <div class="input-group">
  <span class="input-group-addon">Add Image</span>
      <%= f.file_field :image, autofocus: true,class: "form-control" %>
  </div>
  <span class="help-block"></span>

  <div class="input-group">
  <span class="input-group-addon">Add Attachment</span>
      <%= f.file_field :attachement, autofocus: true,class: "form-control" %>
  </div>
  <span class="help-block"></span>
  <div class="input-group">
  <span class="input-group-addon">Add Video</span>
      <%= f.file_field :video, autofocus: true,class: "form-control" %>
  </div>
  <span class="help-block"></span>
  <div class="input-group">
  <span class="input-group-addon">Add Course</span>
  <%= f.collection_select :course_id, @courses, :id, :title, autofocus: true,class: "dropdown-menu" %>
</div>
  <span class="help-block"></span>
  <%= f.submit "Add Lecture",class: "btn btn-lg btn-success btn-block log" %>

<% end %>
</div>
</div>

MOOC/app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form' %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

MOOC/app/views/lectures/index.html.erb
<div class="container">
    <p id="notice"><%= notice %></p>
    <div class="row">
        <center >
            <h1> Lectures</h1>
        </center>
        <br>

        <% @lectures.each do |lecture| %>
        <div class="col-sm-6 col-md-3">
            <div class="thumbnail">
                <%= image_tag lecture.image %>
                <div class="caption">
                    <p><%= lecture.title %></p>
                    <p>
                        <%= link_to'Show' , lecture,class: "fa fa-eye" %>
                        <%  if current_user.is_instructor %>
                        <% if lecture.try(:user).try(:id)==current_user.id %>
                        <%= link_to 'Edit', edit_lecture_path(lecture),class: "fa fa-pencil" %>
                        <%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' },class: "fa fa-trash-o"  %></td>
                    <% end %>
                    <% end %>
                </p>
            </div>
        </div>
    </div>
    <% end %>
</div>
<br>

<%  if current_user.is_instructor %>

<%= link_to 'New Lecture', new_lecture_path,class: "btn btn-success"  %>
<% end %>
</div>
<br>

MOOC/app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form' %>

<%= link_to 'Back', lectures_path %>

MOOC/app/views/lectures/show.html.erb
<div class="container">
    <p id="notice"><%= notice %></p>
    <div class="row">
        <!-- Blog Post -->
        <div class="col-sm-8">
            <div class="blog-post blog-single-post">
                <div class="single-post-title">
                    <center>
                        <h2><%= @lecture.title %></h2>
                    </center>
                </div>

                <div class="single-post-image">
                    <%= image_tag @lecture.image, :size => "600x400" %>
                </div>
                <div class="single-post-info">

                    <strong>Created by:</strong><%= @lecture.try(:user).try(:name) %>
                    <br>

                    <strong>Course:</strong>
                    <%= @lecture.try(:course).try(:title) %>
                    <br>
                    <%= link_to like_lecture_path(@lecture), method: :put do %>
                    Like
                    <%= @lecture.get_upvotes.size %>
                    <% end %>
                    <%= link_to dislike_lecture_path(@lecture), method: :put do %>
                    dislike
                    <%= @lecture.get_downvotes.size %>
                    <% end %>
                    <% if current_user %>
                    <% unless current_user.lectures.include?(@lecture) %>
                    <td>
                        <%= link_to 'spam',spam_lecture_path(@lecture),method: :put %>

                    </td>
                <% else %>
                    <td>
                        <%= link_to 'unspam',unspam_lecture_path(@lecture),method: :delete %>

                    </td>

                    <% end %>

                    <% end %>

                </div>
                <div class="single-post-content">
                    <%=  raw @lecture.content %>
                    <p>
                        <center>
                            <%= video_tag "#{@lecture.video_url}", :size => "400x250", :controls => true %>
                        </center>
                        <strong>Attachement:</strong>
                        <%= link_to 'Download', @lecture.attachement.url %>

                    </p>
                    <h2>Comments</h2 </div>

                    <%= render 'comments/comment' %>
                    <% if current_user.is_instructor %>
                    <% if @lecture.try(:user).try(:id)==current_user.id %>
                    <%= link_to 'Edit', edit_lecture_path(@lecture) %>|
                    <% end %>
                    <% end %>

                    <%= link_to 'Back', lectures_path %>
                </div>

            </div>
        </div>
    </div>
</div>
<br>