MOOC/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :lectures do
      resources :comments
      collection do
        get 'download'
      end
      member do
        put "like", to: "lectures#upvote"
        put "dislike", to: "lectures#downvote"
        put :spam
        delete :unspam
  end

end
  resources :courses
  get 'welcome/index'

  get 'pages/index'

  get 'pages/index'

  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations" }

  root 'welcome#index'

end

MOOC/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MOOC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
     <div class="container">
       <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <a class="navbar-brand" href="#">Mo<span>oc</span></a>
       </div>
       <div class="collapse navbar-collapse" id="myNavbar">
       <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Home',root_path %></li>
         <li><%= link_to 'Courses', courses_path %></li>
         <li><%= link_to 'Lectures', lectures_path %></li>
         <% if user_signed_in? %>
         <li> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </li>
         <li><a> Welcome <%= current_user.try(:name) %> </a></li>
             <% else %>
             <li> <%= link_to "Sign in", new_user_session_path, :method => :GET %> </li>
         <% end%>
       </ul>
       </div>
     </div>
   </nav>

    <p class="notice"><%= notice %></p>
           <p class="alert"><%= alert %></p>

<%= yield %>
<!--Footer-->


<footer id="footer" class="footer">
  <div class="container text-center">

  <h3>Start Your Free Course Now!</h3>

  <form class="mc-trial row">
    <div class="form-group col-md-3 col-md-offset-2 col-sm-4">
      <div class=" controls">
        <input name="name" placeholder="Enter Your Name" class="form-control" type="text">
      </div>
    </div><!-- End email input -->
    <div class="form-group col-md-3 col-sm-4">
      <div class=" controls">
        <input name="EMAIL" placeholder="Enter Your email" class="form-control" type="email">
      </div>
    </div><!-- End email input -->
    <div class="col-md-2 col-sm-4">
      <p>
        <button name="submit" type="submit" class="btn btn-block btn-submit">
        Submit <i class="fa fa-arrow-right"></i></button>
      </p>
    </div>
  </form><!-- End newsletter-form -->
  <ul class="social-links">
    <li><a href="#link"><i class="fa fa-twitter fa-fw"></i></a></li>
    <li><a href="#link"><i class="fa fa-facebook fa-fw"></i></a></li>
    <li><a href="#link"><i class="fa fa-google-plus fa-fw"></i></a></li>
    <li><a href="#link"><i class="fa fa-dribbble fa-fw"></i></a></li>
    <li><a href="#link"><i class="fa fa-linkedin fa-fw"></i></a></li>
  </ul>
    ©2017 Mooc . All rights reserved

  </div>
</footer>

</body>
</html>